//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.31 at 01:28:25 PM IST 
//


package com.trebeyainterview.spring_boot_soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.trebeyainterview.spring_boot_soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.trebeyainterview.spring_boot_soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAccountRequest }
     * 
     */
    public GetAccountRequest createGetAccountRequest() {
        return new GetAccountRequest();
    }

    /**
     * Create an instance of {@link GetAccountResponse }
     * 
     */
    public GetAccountResponse createGetAccountResponse() {
        return new GetAccountResponse();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link GetBalanceRequest }
     * 
     */
    public GetBalanceRequest createGetBalanceRequest() {
        return new GetBalanceRequest();
    }

    /**
     * Create an instance of {@link GetBalanceResponse }
     * 
     */
    public GetBalanceResponse createGetBalanceResponse() {
        return new GetBalanceResponse();
    }

    /**
     * Create an instance of {@link OwnAccountTransferRequest }
     * 
     */
    public OwnAccountTransferRequest createOwnAccountTransferRequest() {
        return new OwnAccountTransferRequest();
    }

    /**
     * Create an instance of {@link OwnAccountTransferResponse }
     * 
     */
    public OwnAccountTransferResponse createOwnAccountTransferResponse() {
        return new OwnAccountTransferResponse();
    }

    /**
     * Create an instance of {@link OwnTransferOutput }
     * 
     */
    public OwnTransferOutput createOwnTransferOutput() {
        return new OwnTransferOutput();
    }

    /**
     * Create an instance of {@link InterAccountTransferRequest }
     * 
     */
    public InterAccountTransferRequest createInterAccountTransferRequest() {
        return new InterAccountTransferRequest();
    }

    /**
     * Create an instance of {@link InterAccountTransferResponse }
     * 
     */
    public InterAccountTransferResponse createInterAccountTransferResponse() {
        return new InterAccountTransferResponse();
    }

    /**
     * Create an instance of {@link InterTransferOutput }
     * 
     */
    public InterTransferOutput createInterTransferOutput() {
        return new InterTransferOutput();
    }

}
