//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.31 at 01:28:25 PM IST 
//


package com.trebeyainterview.spring_boot_soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ownTransferOutput" type="{http://www.trebeyainterview.com/spring-boot-soap}ownTransferOutput"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ownTransferOutput"
})
@XmlRootElement(name = "ownAccountTransferResponse")
public class OwnAccountTransferResponse {

    @XmlElement(required = true)
    protected OwnTransferOutput ownTransferOutput;

    /**
     * Gets the value of the ownTransferOutput property.
     * 
     * @return
     *     possible object is
     *     {@link OwnTransferOutput }
     *     
     */
    public OwnTransferOutput getOwnTransferOutput() {
        return ownTransferOutput;
    }

    /**
     * Sets the value of the ownTransferOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnTransferOutput }
     *     
     */
    public void setOwnTransferOutput(OwnTransferOutput value) {
        this.ownTransferOutput = value;
    }

}
